apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: github-actions-gke-enterprisebus-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: github-actions-gke-enterprisebus
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: process_cpu_usage
        target:
          type: Utilization
          averageUtilization: 20
