apiVersion: v1
kind: Service
metadata:
  name: github-actions-gke-enterprisebus
spec:
  selector:
    app: github-actions-gke-enterprisebus
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080