apiVersion: v1
kind: Service
metadata:
  name: github-actions-gke-enterprisebus
spec:
  selector:
    app: github-actions-gke-enterprisebus
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: prometheus
      port: 9090
      targetPort: 9090