server:
  port: 8080

management:
  enable:
    process:
      cpu:
        usage: true

  endpoints:
    web:
      exposure:
        include: '*'

  prometheus:
    metrics:
      export:
        enabled: true